name: Audit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-22.04
    env:
      GO111MODULE: on
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Verify dependencies
      run: go mod verify

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.64.8

    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y make curl
        sudo mkdir -p /usr/libexec/docker/cli-plugins
        sudo curl -SL https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64 -o /usr/libexec/docker/cli-plugins/docker-compose
        sudo chmod +x /usr/libexec/docker/cli-plugins/docker-compose

    - name: Run tests
      run: make test
